on: [workflow_dispatch]

name: GitHub Actions Ipynb preflight
jobs:
  ipynb_for_publishing:
    runs-on: ubuntu-latest
    name: Ipynb for preflight
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: preflight check
        id: preflight
        uses: c2dh/journal-of-digital-history-ipynb-preflight-action@master
        with:
          notebook: 'article.ipynb'
          functions: 'checkkernel,checkcitation,checkhtml,checkoutput,checktags,checkurls,checkjavascript'
          output_md: 'report.md'
      # Use the output from the `preflight` step
      - name: Use the output
        run: echo "number of cells ${{ steps.preflight.outputs.size }} - output ${{ steps.preflight.outputs.checkmd }}"
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.md'
